[pytest]
python_files = teste_*.py
addopts = -v -ra --tb=short --color=yes --alluredir=allure-results --clean-alluredir
markers =
    login: testes relacionados ao fluxo de login
    cadastro: testes relacionados ao fluxo de cadastro
    carrinho: testes relacionados ao fluxo de compras
    detalhesConta: testes relacionados a edição de dados da conta
    endereco: testes relacionados ao fluxo de alteração de endereços
